version: '3.8'

volumes:
  supportbotdashboard_data_volume:
    external: true

services:
  support-bot-dashboard:
    container_name: support_bot_dashboard
    restart: always
    build: .
    volumes:
      - supportbotdashboard_data_volume:/data
    extra_hosts:
      - "localhost:${HOST_IP_ADDRESS}"
    networks:
      - grpc_backend
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - support_bot_dashboard
networks:
  grpc_backend:
    name: support_bot_grpc_backend
    external: true
  web_network:
    driver: bridge
 